[package]
name = "ror2_command"
version = "0.1.0"
authors = ["dxb"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.8", features = [ "winuser", "impl-default" ] }
image = { version = "0.23.2" }
