[package]
name = "ror2_command"
version = "0.1.0"
authors = ["dxb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = { version = "0.22.0" }
winit_input_helper = "0.6.0"
pixels = "0.0.2"
